### ISSUE TITLE
Registration UI

### ISSUE THREAD

**Issue by HarrisonBanh** [Ebikan/RatPatrol#14]
- [x]  Widgets for the user to enter username and password

- [x] Widget to cancel/add the user

**Comment by MultiDream** [comment]
Functions Complete, but may not work. Not sure how to check the backing Database.

**Comment by MultiDream** [comment]
It is done, but does not handle errors that well.
Also, not sure how to confirm the data is properly stored.

**Comment by MultiDream** [comment]
Done.
